### ISSUE TITLE
[Help] How to create the outer wave example?

### ISSUE THREAD

**Issue by vramosx** [glorylab/wave#38]
Hi! Thanks for this awesome package. 

I was trying to create the same result like the outer wave example:

![image](https://user-images.githubusercontent.com/19556401/145883444-bb04e21d-910c-4350-9e3c-3b0863aefd13.png)

In the available example there is also no such version. Can you please provide an example of this?

Thanks!

**Comment by RockerFlower** [comment]
This is because the `blur` property is set in `CustomConfig`. 

```
WaveWidget(
    // ...
    config: CustomConfig(
        // ...
        blur: MaskFilter.blur(BlurStyle.outer, 2),
    ),
),
```
