### ISSUE TITLE
Circle view needed

### ISSUE THREAD

**Issue by Kayuemkhan** [glorylab/wave#42]
**Is your feature request related to a problem? Please describe.**
I need waveview In circle 
**Describe the solution you'd like**
I need waveview In circle . But, It is by default only work with rectangular. no Options for circle view.

**Comment by igmt** [comment]
You can simply use a container with decoration shape circle and clipBehavior set.
I needed the same and found out this works well.
```
Container(
    clipBehavior: Clip.antiAlias,
    height: 150,
    decoration: const BoxDecoration(
        shape: BoxShape.circle,
    ),
    child: WaveWidget(...),
)
```
<img width="343" alt="Rounded waves" src="https://user-images.githubusercontent.com/1704847/163118543-bf8f1882-795b-43f7-bc98-53bdb9c2e038.png">

**Comment by Kayuemkhan** [comment]
Thanks...
