### ISSUE TITLE
Cannot flip widget

### ISSUE THREAD

**Issue by adrianvintu** [glorylab/wave#44]
Using the  git example https://github.com/glorylab/wave, I am trying to flip the widget. either by flipping the card

````
Transform(
  transform: Matrix4.rotationY(math.pi),
  child: _buildCard(
````
or by flipping the control
```
Card(
...
  child: Transform(
    transform: Matrix4.rotationY(math.pi),
    child: WaveWidget(
      config: config,
      backgroundColor: backgroundColor,
      backgroundImage: backgroundImage,
      size: Size(double.infinity, double.infinity),
      waveAmplitude: 0,
    ),
),
```
Both methods fail - first method completely hides the card, the second method shows empty card.

Can you please check this?

Thank you!

**Comment by abenkdh** [comment]
Use transform scale

`Transform.scale(
              scaleY: -1,
              child: WaveWidget( ),
            )`

**Comment by Haris2v** [comment]
Thank you @abenkdh. Your solution worked like a charm!
@adrianvintu Maybe you should close this issue. Thank you
