### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by RyoheiTomiyama** [glorylab/wave#48]
**Describe the bug**
I think colors: colors is a mistake for `colors: _colors` in [README.md.](https://github.com/glorylab/wave#getting-started)

```dart
WaveWidget(
    config: CustomConfig(
        colors: colors,
        durations: _durations,
```

**Expected behavior**
```dart
WaveWidget(
    config: CustomConfig(
        colors: _colors,
        durations: _durations,
```

**Screenshots**

<img width="1286" alt="スクリーンショット 2023-08-24 11 52 42" src="https://github.com/glorylab/wave/assets/10805686/c4dd4d51-00c4-48c9-b539-a4a13fa01b58">

**Comment by RockerFlower** [comment]
Thank you!
